### ISSUE TITLE
CVE-2023-27372

### ISSUE THREAD

**Issue by WHITEH0ST** [Chocapikk/Chocapikk#1]
Hello, 

This tool was taken down from your GITHUB. Any way i could fork or get source?

Thanks.

**Comment by Chocapikk** [comment]
Hello. Yes I have decided to make absolutely all my exploits private. 

Many people wanted to use it in a malicious way. I won't be posting exploits on github anymore.

It's sad to come to this. I do not want to be responsible for computer attacks because of my modified exploits. 

You can read the README of my account to understand. 

Cordially,

Chocapikk.

**Comment by Chocapikk** [comment]
If you have other questions, do not hesitate. Otherwise close the issue please

**Comment by WHITEH0ST** [comment]
I humbly request that you send me the source code, 


I read your code on the CVE while I stopped by at the restaurant for some juice and found it interesting, now im on my PC to find out it has been taken down.

At your earliest convenience if you can share the source code, I would really appreciate it.

Cheers.

**Comment by Chocapikk** [comment]
Hello, sorry for the late reply. As explained, I can no longer provide an exploit to anyone because it can be misused. Until further notice.
